SELECT * FROM T_MVD_PROYECTO_DOCUMENTO WHERE NU_ID_PROYECTO_NORMATIVO = 161 AND TX_REGISTRO_ACTIVO = '1' AND NU_ID_DOCUMENTO_CATEGORIA = 4

SELECT * FROM T_GED_DOCUMENTO_CATEGORIA
SELECT * FROM T_GED_PERSONA

//SE CIERRA CON EL FLAG QUE ESTA EN T_MAC_PROYECTO_NROMATIVO
SELECT * FROM T_MAC_PROYECTO_NORMATIVO

SELECT * FROM T_GED_PERSONA 
UPDATE T_GED_PERSONA SET TX_PERSONA_CORREO = 'kevinmtip@gmail.com' WHERE NU_ID_PERSONA = 141
COMMIT;
