SELECT * FROM T_MVD_CONFLICTO_ESTADO WHERE NU_ID_CONFLICTO = 1201 AND TX_CONFLICTO_ESTADO_ACTIVO = 1
SELECT * FROM T_GED_CONFLICTO
---CONSULTA PARA LISTAR TODOS LOS CONFLICTOS

WITH 
    CATALOGO AS ( 
    SELECT   
        NU_ID_ITEM,    
        TX_ITEM_VALOR,    
        TX_ITEM_ETIQUETA   
    FROM T_MAP_CATALOGO     
    WHERE NU_ID_CATALOGO IN(        
        SELECT             
            NU_ID_ITEM       
        FROM T_MAP_CATALOGO        
    WHERE TX_ITEM_VALOR = 'CE'  ) ) 
    SELECT 
        TMC.NU_ID_CONFLICTO idConflicto,        
        TMC.FE_CONFLICTO_FECHA conflictoFecha,        
        TMC.TX_CONFLICTO_CODIGO conflictoCodigo,       
        TMCE.TX_CONFLICTO_ROTULO conflictoRotulo,        
        TMCE.TX_ETAPA_CAT_VAL etapaCatValor,        
        TMC.TX_ITEM_ETIQUETA etiqueta,
        TMCE.TX_CONFLICTO_ACTIVO,--
        LISTAGG(VMS.TX_SUBSECTOR_NOMBRE, ', ') WITHIN GROUP( ORDER BY VMS.TX_SUBSECTOR_NOMBRE ) as conflictoSectores  
        FROM SISCONSA.T_MAC_CONFLICTO TMC  
        LEFT OUTER JOIN T_MVD_CONFLICTO_ESTADO TMCE ON TMC.NU_ID_CONFLICTO = TMCE.NU_ID_CONFLICTO AND TMCE.TX_CONFLICTO_ESTADO_ACTIVO = '1'  
        LEFT OUTER JOIN T_MVD_CONFLICTO_SECTOR TMCS ON TMC.NU_ID_CONFLICTO = TMCS.NU_ID_CONFLICTO  
        LEFT OUTER JOIN VW_MAD_SUBSECTOR VMS ON TMCS.NU_ID_SECTOR = VMS.NU_ID_SUBSECTOR  
        LEFT OUTER JOIN CATALOGO TMC ON TMCE.TX_ETAPA_CAT_VAL = TMC.TX_ITEM_VALOR  
        WHERE TMC.TX_REGISTRO_ACTIVO = '1'  
        GROUP BY TMC.NU_ID_CONFLICTO, TMC.FE_CONFLICTO_FECHA, TMCE.TX_CONFLICTO_ROTULO, TMCE.TX_ETAPA_CAT_VAL, TMC.TX_CONFLICTO_CODIGO ,TMC.TX_ITEM_ETIQUETA, TMCE.TX_CONFLICTO_ACTIVO  --
        ORDER BY TMC.NU_ID_CONFLICTO DESC
    
----CONSULTAR PARA LISTAR LOS COLORES DEL MAPA


--------------------------------------------------------
--  DDL for View VW_REP_MAPA
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SISCONSA"."VW_REP_MAPA" ("TX_ID_UBI_DPTO", "TX_DEPARTAMENTO", "TX_COLOR", "ORDEN") AS 
  WITH Departamento as (
    SELECT 
        TX_ID_UBI_DPTO,
        TX_DEPARTAMENTO
    FROM VW_MAP_UBIGEO
    GROUP BY   
        TX_ID_UBI_DPTO,
        TX_DEPARTAMENTO
	), Sensibilidad as (
	    SELECT 
	        NU_ID_CONFLICTO,
	        TX_SENSIBILIDAD_CAT_VAL,
	        CASE TX_SENSIBILIDAD_CAT_VAL WHEN 'A1' THEN 1
	                                     WHEN 'M1' THEN 2
	                                     WHEN 'B1' THEN 3
	                                     ELSE 0
	        END AS TX_COLOR
	    FROM T_MVD_CONFLICTO_ESTADO
	    WHERE TX_REGISTRO_ACTIVO = '1' AND TX_CONFLICTO_ESTADO_ACTIVO = '1'  AND TX_CONFLICTO_ESTADO_ACTIVO = '1' AND TX_CONFLICTO_ACTIVO = '1'
	), Estado as (
	    SELECT 
	        NU_ID_CONFLICTO, 
	        TX_ZONA_ID_UBIGEO,
	        CASE WHEN LENGTH(TX_ZONA_ID_UBIGEO)>1 THEN  SUBSTR(TX_ZONA_ID_UBIGEO,0,2) ELSE TX_ZONA_ID_UBIGEO END AS TX_ID_UBI_DPTO
	    FROM T_MVD_CONFLICTO_ZONA
	    WHERE TX_REGISTRO_ACTIVO = '1'
	), Resumen as (
	    SELECT
	        E.TX_ID_UBI_DPTO,
	        D.TX_DEPARTAMENTO,
	        S.TX_COLOR
	    FROM T_MAC_CONFLICTO C
	    INNER JOIN Sensibilidad S ON C.NU_ID_CONFLICTO = S.NU_ID_CONFLICTO
	    INNER JOIN Estado E ON C.NU_ID_CONFLICTO = E.NU_ID_CONFLICTO
	    INNER JOIN Departamento D on E.TX_ID_UBI_DPTO = D.TX_ID_UBI_DPTO
	    WHERE C.TX_REGISTRO_ACTIVO = '1'
	    GROUP BY  
	        E.TX_ID_UBI_DPTO,
	        D.TX_DEPARTAMENTO,
	        S.TX_COLOR
	), Filtrado as (
	SELECT 
	    TX_ID_UBI_DPTO,
	    TX_DEPARTAMENTO,
	    TX_COLOR,
	    ROW_NUMBER() OVER(PARTITION BY TX_ID_UBI_DPTO ORDER BY TX_COLOR ASC ) ORDEN
	FROM Resumen
	)
	SELECT  "TX_ID_UBI_DPTO","TX_DEPARTAMENTO","TX_COLOR","ORDEN" FROM FILTRADO WHERE ORDEN = 1
;

----MAPA DE MEDIDAS DE FUERZA

--------------------------------------------------------
--  DDL for View VW_MED_MAPA
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SISCONSA"."VW_MED_MAPA" ("TX_ID_UBI_DPTO", "TX_DEPARTAMENTO", "TX_COLOR", "ORDEN", "FE_MFUERZA_NOTICIA_FECHA") AS 
  WITH Departamento as (
		SELECT
			TX_ID_UBI_DPTO,
			TX_DEPARTAMENTO
		FROM
			SISCONSA.VW_MAP_UBIGEO
		GROUP BY
			TX_ID_UBI_DPTO,
			TX_DEPARTAMENTO
	), Sensibilidad as (
		SELECT
			NU_ID_MEDIDA_FUERZA,
			TX_MFUERZA_INTENSIDAD_VALOR,
			CASE
				TX_MFUERZA_INTENSIDAD_VALOR WHEN 'A1' THEN 1
				WHEN 'M2' THEN 2
				WHEN 'B3' THEN 3
				ELSE 0
			END AS TX_COLOR
		FROM
			SISCONSA.T_GED_MEDIDA_FUERZA
		WHERE
			TX_REGISTRO_ACTIVO = '1'
	), Estado as (
		SELECT
			NU_ID_MEDIDA_FUERZA,
			TX_ID_UBI_DPTO,
			FE_MFUERZA_NOTICIA_FECHA,
			CASE
				WHEN LENGTH(TX_ID_UBI_DPTO)>1 THEN SUBSTR(TX_ID_UBI_DPTO, 0, 2)
				ELSE TX_ID_UBI_DPTO
			END -- AS TX_ID_UBI_DPTO
			    FROM SISCONSA.T_GED_MEDIDA_FUERZA
			    WHERE TX_REGISTRO_ACTIVO = '1'
	), Resumen as (
		SELECT
			E.TX_ID_UBI_DPTO,
			D.TX_DEPARTAMENTO,
			S.TX_COLOR,
			E.FE_MFUERZA_NOTICIA_FECHA
		FROM
			SISCONSA.T_GED_MEDIDA_FUERZA C
		INNER JOIN Sensibilidad S ON
			C.NU_ID_MEDIDA_FUERZA = S.NU_ID_MEDIDA_FUERZA
		INNER JOIN Estado E ON
			C.NU_ID_MEDIDA_FUERZA = E.NU_ID_MEDIDA_FUERZA
		INNER JOIN Departamento D ON
			E.TX_ID_UBI_DPTO = D.TX_ID_UBI_DPTO
		WHERE
			C.TX_REGISTRO_ACTIVO = '1'
		GROUP BY
			E.TX_ID_UBI_DPTO,
			D.TX_DEPARTAMENTO,
			S.TX_COLOR,
			E.FE_MFUERZA_NOTICIA_FECHA
	), Filtrado as (
		SELECT
			TX_ID_UBI_DPTO,
			TX_DEPARTAMENTO,
			TX_COLOR,
			FE_MFUERZA_NOTICIA_FECHA,
			ROW_NUMBER() OVER(PARTITION BY TX_ID_UBI_DPTO ORDER BY TX_COLOR ASC ) ORDEN
		FROM
			Resumen
	)
		SELECT
			"TX_ID_UBI_DPTO",
			"TX_DEPARTAMENTO",
			"TX_COLOR",
			"ORDEN",
			"FE_MFUERZA_NOTICIA_FECHA"
		FROM
			FILTRADO
		WHERE
			ORDEN = 1
			--AND FE_MFUERZA_NOTICIA_FECHA >= SYSDATE -7

;

    
    
    
    