--UNIDADES FISCALIZABLES POR CONFLICTO
SELECT 
    CUF.NU_ID_CONFLICTO_UNI_FISCA idConflictoUniFisca, 
   --MA.TX_ADMINISTRADO_CODIGO administradoCodigo , 
    --MA.TX_ID_ADMINISTRADO idAdministrado , 
    --MUF.TX_UNI_FISCA_CODIGO fiscaCodigo , 
    --MUF.TX_UNI_FISCA_NOMBRE uniFiscaNombre , 
    --MUF.TX_UNI_FISCA_CODIGO_REF fiscaCodigoRef , 
    --CUF.TX_ID_UNI_FISCA uniFisca , 
    --CUF.TX_CONF_UNI_FISCA_OBSERVACION confUniFiscaObservacion, 
    --CUF.FE_CONF_UNI_FISCA_FEC_INGRESO confUniFiscaFecIngreso , 
    --CUF.FE_CONF_UNI_FISCA_FEC_SALIDA confUniFiscaFecSalida , 
    CUF.TX_CONF_UNI_FISCA_ACTIVO confUniFiscaActivo  
FROM SISCONSA.T_MVD_CONFLICTO_UNI_FISCA CUF 
INNER JOIN VW_MAD_UNI_FISCA MUF ON MUF.TX_ID_UNI_FISCA = CUF.TX_ID_UNI_FISCA 
INNER JOIN VW_MVD_ADM_UNI_FISCA MAUF ON MAUF.TX_ID_UNI_FISCA = MUF.TX_ID_UNI_FISCA 
INNER JOIN VW_MAD_ADMINISTRADO MA ON MA.TX_ID_ADMINISTRADO = MAUF.TX_ID_ADMINISTRADO 
INNER JOIN T_MVD_CONFLICTO_ADMINISTRADO MVA ON MVA.TX_ID_ADMINISTRADO = MA.TX_ID_ADMINISTRADO 
WHERE (CUF.NU_ID_CONFLICTO = 41 AND MVA.NU_ID_CONFLICTO = 41 AND CUF.TX_REGISTRO_ACTIVO = '1' AND MVA.TX_REGISTRO_ACTIVO = '1')
GROUP BY CUF.NU_ID_CONFLICTO_UNI_FISCA, CUF.TX_CONF_UNI_FISCA_ACTIVO, MA.TX_ID_ADMINISTRADO

SELECT * FROM VW_MAD_ADMINISTRADO
SELECT * FROM VW_MAD_UNI_FISCA WHERE TX_ID_UNI_FISCA = 'U0000000'
SELECT * FROM VW_MVD_ADM_UNI_FISCA WHERE TX_ID_UNI_FISCA = 'U0000000'
SELECT * FROM T_MVD_CONFLICTO_UNI_FISCA
SELECT * FROM T_MVD_CONFLICTO_ADMINISTRADO WHERE NU_ID_CONFLICTO = 41

